#!/usr/local/bin/php
<?php

namespace Sodigital\Services\Regex;

use \Sodigital\Services\Database\Adapter;
use Retrinko\Ini\IniFile;

require_once(dirname(__FILE__)."/vendor/autoload.php");
require_once(dirname(__FILE__)."/lib/autoload.php");


$dbConfig = IniFile::load(dirname(__FILE__)."/config/db.ini");

$db = new Adapter($dbConfig);

$service = new Regex($db);

$service->run();